### PR TITLE
Create GetRepoDetails.py

### PR DESCRIPTION
**Pull request by shuvday**

### CODE REVIEW

**Comment by pavithra-mahadev** [comment]
Is vcenter password not required to get the repository profiles?

**Comment by prasadrao-dell** [comment]
Yes, I think it is needed and also the vC UUID

**Comment by shuvaday** [comment]
@prasadrao-dell  do the user need to pass UUID manually or we need to fetch internally.

**Comment by prasadrao-dell** [comment]
@shuvaday ...You may accept the UUID of the vcenter from the user for which the credentials were also provided

**Pull request merged**
